[tools]
# lang
bun = "latest"
node = "20.10.0"
go = "1.25.4"
golangci-lint = "latest"
task = "latest"
# mise use -g java@zulu-8.90.0.19 or zulu-11.84.17.0 or zulu-17.62.17.0 or zulu-21.46.19.0
java = "zulu-21.46.19.0"
python = "3.13.9"
uv = "latest"
poetry = "latest"
rust = "latest"
# infra
docker-cli = "latest"
docker-compose = "latest"
kubectl = "latest"
k9s = "latest"
mysql = "8.0.33"
postgres = "16.11"
redis = "8.2.0"
terraform = "latest"
aws-cli = "latest"
aws-vault = "latest"
gcloud = "latest"

[tasks.python-format]
alias = "ruff-format"
description = "ruffを使ってコードformatを実行"
run = "uv run ruff check . --fix;uv run ruff format ."

[tasks.python-lint]
alias = "tox"
description = "toxを実行"
run = "uv run tox"

[tasks.tensorboard]
alias = "tensorboard"
description = "tensorboardを起動"
run = "tensorboard --port 6006 --logdir ./ --host 0.0.0.0"

[tasks.jupyterlab]
alias = "jupyter"
description = "jupyterlabを起動"
run = "jupyter lab --port=8888 --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''"

[tasks.go-build]
alias = "go-build"
description = "goでbuildするコマンド"
run = "GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build"

[tasks.docker-compose]
alias = "docker-compose-build"
description = "compose fileを起動するコマンド"
run = "docker compose up -d --build"

[tasks.homebrew-update]
alias = "brew-update"
description = "homebrew, packageをアプデする"
run = "brew update --auto-update;brew upgrade;brew cleanup"

[tasks.homebrew-dump]
alias = "brew-dump"
description = "homebrewの依存関係を吐き出す"
run = "rm ~/.Brewfile;brew bundle dump --global"

[tasks.git-head-commit-reset]
alias = "git-head-commit-rest"
description = "git commitの直近1件を取り消す"
run = "git reset --soft HEAD^"
